import express from "express";
import {
  createAgent,
  getAgents,
  getUserRecommendations,
  createRecommendation,
  createNegotiation,
  updateNegotiation,
  performFraudCheck,
  analyzeReviewSentiment,
  getAIDashboard,
  getMyRecommendations,
  checkAIHealth,
  chatBookingSupport,
  clearBookingSupportHistory,
  checkBookingSupportHealth,
  getBookingSupportStats,
} from "../controller/ai.controller.js";
import {
  createReview,
  getEventReviews,
  getUserReviews,
} from "../controller/review.controller.js";
import {
  getBookingWithAIInsights,
  getBookingFraudRisk,
} from "../controller/booking.controller.js";
import {
  getAIRecommendedEvents,
  generateEventRecommendations,
  getEventSentimentAnalysis,
} from "../controller/Event.controller.js";
import { authenticateUser } from "../middleware/authMiddleware.js";
import { protectAdmin } from "../middleware/adminMiddleware.js";

/**
 * ============================================================================
 * BACKEND AI ROUTES
 * ============================================================================
 * 
 * Base Path: /api/ai
 * 
 * These routes handle all AI-related functionality for the Backend API
 * Frontend calls these routes, which then proxy to the AI Agent Service
 * 
 * ============================================================================
 */

const router = express.Router();

// ============================================================================
// SYSTEM ROUTES
// ============================================================================

/**
 * GET /api/ai/health
 * Overall AI system health check
 * Public endpoint - no auth required
 */
router.get("/health", checkAIHealth);

// ============================================================================
// AI AGENT MANAGEMENT ROUTES (Admin Only)
// ============================================================================

/**
 * POST /api/ai/agents
 * Create a new AI agent
 * Admin only
 */
router.post("/agents", authenticateUser, protectAdmin, createAgent);

/**
 * GET /api/ai/agents
 * List all AI agents
 * Admin only
 */
router.get("/agents", authenticateUser, protectAdmin, getAgents);

// ============================================================================
// AI RECOMMENDATION ROUTES
// ============================================================================

/**
 * GET /api/ai/recommendations/user/:userId
 * Get AI recommendations for a specific user
 * Requires authentication
 */
router.get(
  "/recommendations/user/:userId",
  authenticateUser,
  getUserRecommendations
);

/**
 * GET /api/ai/recommendations/me
 * Get AI recommended events for current user
 * Requires authentication
 */
router.get("/recommendations/me", authenticateUser, getAIRecommendedEvents);

/**
 * POST /api/ai/recommendations
 * Create a new recommendation
 * Requires authentication
 */
router.post("/recommendations", authenticateUser, createRecommendation);

/**
 * POST /api/ai/recommendations/generate
 * Generate recommendations (for AI service)
 * Requires authentication
 */
router.post(
  "/recommendations/generate",
  authenticateUser,
  generateEventRecommendations
);

// ============================================================================
// BOOKING SUPPORT AGENT ROUTES
// ============================================================================

/**
 * POST /api/ai/booking-support/chat
 * 
 * Main chatbot endpoint for booking support
 * Handles FAQ questions, multilingual support, and conversation context
 * 
 * Request Body:
 * {
 *   message: string (required),
 *   sessionId: string (optional - for anonymous users)
 * }
 * 
 * Note: userId is extracted from auth middleware (req.user.id)
 * For anonymous users, use sessionId instead
 */
router.post("/booking-support/chat", authenticateUser, chatBookingSupport);

/**
 * POST /api/ai/booking-support/chat-anonymous
 * 
 * Anonymous chat endpoint (no authentication required)
 * Useful for users who aren't logged in yet
 * 
 * Request Body:
 * {
 *   message: string (required),
 *   sessionId: string (optional - generated by frontend)
 * }
 */
router.post("/booking-support/chat-anonymous", chatBookingSupport);

/**
 * POST /api/ai/booking-support/clear-history
 * 
 * Clear conversation history for current user
 * Useful for "New Conversation" button
 * 
 * Requires authentication
 */
router.post(
  "/booking-support/clear-history",
  authenticateUser,
  clearBookingSupportHistory
);

/**
 * GET /api/ai/booking-support/health
 * 
 * Check booking support agent health
 * Returns detailed component status
 * 
 * Public endpoint for monitoring
 */
router.get("/booking-support/health", checkBookingSupportHealth);

/**
 * GET /api/ai/booking-support/stats
 * 
 * Get booking support agent statistics
 * Admin only - for monitoring dashboards
 */
router.get(
  "/booking-support/stats",
  authenticateUser,
  protectAdmin,
  getBookingSupportStats
);

// ============================================================================
// AI NEGOTIATION ROUTES
// ============================================================================

/**
 * POST /api/ai/negotiations
 * Create a new negotiation
 */
router.post("/negotiations", authenticateUser, createNegotiation);

/**
 * PUT /api/ai/negotiations/:id
 * Update negotiation status
 */
router.put("/negotiations/:id", authenticateUser, updateNegotiation);

// ============================================================================
// AI FRAUD CHECK ROUTES (Admin Only)
// ============================================================================

/**
 * POST /api/ai/fraud-check/:bookingId
 * Perform fraud check on a booking
 * Admin only
 */
router.post(
  "/fraud-check/:bookingId",
  authenticateUser,
  protectAdmin,
  performFraudCheck
);

/**
 * GET /api/ai/fraud-check/booking/:id
 * Get fraud risk for a booking
 */
router.get("/fraud-check/booking/:id", authenticateUser, getBookingFraudRisk);

// ============================================================================
// AI SENTIMENT ANALYSIS ROUTES
// ============================================================================

/**
 * POST /api/ai/sentiment-analysis/:reviewId
 * Analyze sentiment of a review
 * Admin only
 */
router.post(
  "/sentiment-analysis/:reviewId",
  authenticateUser,
  protectAdmin,
  analyzeReviewSentiment
);

/**
 * GET /api/ai/sentiment-analysis/event/:id
 * Get sentiment analysis for an event
 */
router.get(
  "/sentiment-analysis/event/:id",
  authenticateUser,
  getEventSentimentAnalysis
);

// ============================================================================
// REVIEW ROUTES (with AI integration)
// ============================================================================

/**
 * POST /api/ai/reviews
 * Create a new review
 */
router.post("/reviews", authenticateUser, createReview);

/**
 * GET /api/ai/reviews/event/:eventId
 * Get all reviews for an event
 */
router.get("/reviews/event/:eventId", getEventReviews);

/**
 * GET /api/ai/reviews/me
 * Get current user's reviews
 */
router.get("/reviews/me", authenticateUser, getUserReviews);

// ============================================================================
// BOOKING AI DATA ROUTES
// ============================================================================

/**
 * GET /api/ai/bookings/:id/insights
 * Get AI insights for a booking
 */
router.get(
  "/bookings/:id/insights",
  authenticateUser,
  getBookingWithAIInsights
);

/**
 * GET /api/ai/bookings/:id/fraud-risk
 * Get fraud risk assessment for a booking
 */
router.get("/bookings/:id/fraud-risk", authenticateUser, getBookingFraudRisk);

// ============================================================================
// AI DASHBOARD (Admin Only)
// ============================================================================

/**
 * GET /api/ai/dashboard
 * Get comprehensive AI system dashboard
 * Admin only
 */
router.get("/dashboard", authenticateUser, protectAdmin, getAIDashboard);

export default router;